using AutoMapper;
using ApiWorker.Documents.DTOs;
using ApiWorker.Documents.Entities;
using ApiWorker.Documents.Enums;

namespace ApiWorker.Documents.Mappings;

/// <summary>
/// AutoMapper profile for mapping between DTOs and Entities.
/// Keeps mapping logic centralized and testable.
/// </summary>
public sealed class DocumentMappingProfile : Profile
{
    public DocumentMappingProfile()
    {
        // ===== ENTITY → DTO MAPPINGS =====
        // Used when reading data from database to send to mobile app

        /// <summary>
        /// Maps Invoice entity to InvoiceDto for API responses.
        /// Includes computed totals and URLs.
        /// </summary>
        CreateMap<Invoice, InvoiceDto>()
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status.ToString()))
            .ForMember(dest => dest.Customer, opt => opt.MapFrom(src => new CustomerDto
            {
                Name = src.CustomerName ?? string.Empty,
                Phone = src.CustomerPhone,
                Email = src.CustomerEmail,
                AddressLine1 = src.BillingAddressLine1,
                AddressLine2 = src.BillingAddressLine2,
                City = src.BillingCity,
                Country = src.BillingCountry
            }))
            .ForMember(dest => dest.Lines, opt => opt.MapFrom(src => src.Lines))
            .ForMember(dest => dest.Urls, opt => opt.MapFrom(src => new DocumentUrls
            {
                DocxUrl = src.DocxBlobUrl,
                PdfUrl = src.PdfBlobUrl
            }));

        /// <summary>
        /// Maps TransactionalDocumentLine entity to InvoiceLineDto.
        /// Simple 1:1 mapping of properties.
        /// </summary>
        CreateMap<TransactionalDocumentLine, InvoiceLineDto>();

        /// <summary>
        /// Maps Invoice entity to DocumentSummary for list views.
        /// Lightweight DTO with only essential fields.
        /// </summary>
        CreateMap<Invoice, DocumentSummary>()
            .ForMember(dest => dest.RecipientName, opt => opt.MapFrom(src => src.CustomerName))
            .ForMember(dest => dest.PdfUrl, opt => opt.MapFrom(src => src.PdfBlobUrl));

        // ===== DTO → ENTITY MAPPINGS =====
        // Used when creating/updating entities from API requests

        /// <summary>
        /// Maps CreateInvoiceManuallyRequest to Invoice entity.
        /// Sets initial status to Draft and computes totals.
        /// </summary>
        CreateMap<CreateInvoiceManuallyRequest, Invoice>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Generated by database
            .ForMember(dest => dest.Number, opt => opt.Ignore()) // Generated by service
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => DocumentType.Invoice))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => DocumentStatus.Draft))
            .ForMember(dest => dest.CustomerName, opt => opt.MapFrom(src => src.Customer.Name))
            .ForMember(dest => dest.CustomerPhone, opt => opt.MapFrom(src => src.Customer.Phone))
            .ForMember(dest => dest.CustomerEmail, opt => opt.MapFrom(src => src.Customer.Email))
            .ForMember(dest => dest.BillingAddressLine1, opt => opt.MapFrom(src => src.Customer.AddressLine1))
            .ForMember(dest => dest.BillingAddressLine2, opt => opt.MapFrom(src => src.Customer.AddressLine2))
            .ForMember(dest => dest.BillingCity, opt => opt.MapFrom(src => src.Customer.City))
            .ForMember(dest => dest.BillingCountry, opt => opt.MapFrom(src => src.Customer.Country))
            .ForMember(dest => dest.IssuedAt, opt => opt.MapFrom(src => src.IssuedAt ?? DateTimeOffset.UtcNow))
            .ForMember(dest => dest.Lines, opt => opt.MapFrom(src => src.Lines))
            // Computed fields set by service
            .ForMember(dest => dest.Subtotal, opt => opt.Ignore())
            .ForMember(dest => dest.Tax, opt => opt.Ignore())
            .ForMember(dest => dest.Total, opt => opt.Ignore())
            // Audit fields
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => DateTimeOffset.UtcNow))
            .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTimeOffset.UtcNow))
            // Navigation properties
            .ForMember(dest => dest.ShareLogs, opt => opt.Ignore())
            .ForMember(dest => dest.RowVersion, opt => opt.Ignore());

        /// <summary>
        /// Maps InvoiceLineDto to TransactionalDocumentLine entity.
        /// Computes line total from quantity and unit price.
        /// </summary>
        CreateMap<InvoiceLineDto, TransactionalDocumentLine>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Generated by database
            .ForMember(dest => dest.DocumentId, opt => opt.Ignore()) // Set by parent
            .ForMember(dest => dest.TaxRate, opt => opt.MapFrom(src => src.TaxRate ?? 0m))
            .ForMember(dest => dest.LineTotal, opt => opt.MapFrom(src => src.Quantity * src.UnitPrice))
            .ForMember(dest => dest.Document, opt => opt.Ignore()); // Navigation property

        /// <summary>
        /// Maps UpdateInvoiceRequest to Invoice entity.
        /// Only updates provided fields (partial update).
        /// </summary>
        CreateMap<UpdateInvoiceRequest, Invoice>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.InvoiceId))
            .ForMember(dest => dest.CustomerName, opt => opt.MapFrom((src, dest) =>
                src.Customer != null ? src.Customer.Name : dest.CustomerName))
            .ForMember(dest => dest.CustomerPhone, opt => opt.MapFrom((src, dest) =>
                src.Customer != null ? src.Customer.Phone : dest.CustomerPhone))
            .ForMember(dest => dest.CustomerEmail, opt => opt.MapFrom((src, dest) =>
                src.Customer != null ? src.Customer.Email : dest.CustomerEmail))
            .ForMember(dest => dest.DueAt, opt => opt.MapFrom((src, dest) =>
                src.DueAt ?? dest.DueAt))
            .ForMember(dest => dest.Notes, opt => opt.MapFrom((src, dest) =>
                src.Notes ?? dest.Notes))
            .ForMember(dest => dest.Reference, opt => opt.MapFrom((src, dest) =>
                src.Reference ?? dest.Reference))
            .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTimeOffset.UtcNow))
            .ForAllMembers(opt => opt.Condition((src, dest, srcMember) => srcMember != null)); // Only map when source value is provided

        // ===== SHARE LOG MAPPINGS =====

        /// <summary>
        /// Maps ShareDocumentRequest to ShareLog entity for audit trail.
        /// </summary>
        CreateMap<ShareDocumentRequest, ShareLog>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.Target, opt => opt.MapFrom(src => src.Target ?? string.Empty))
            .ForMember(dest => dest.Channel, opt => opt.MapFrom(src => Enum.Parse<ShareChannel>(src.Channel)))
            .ForMember(dest => dest.SentAt, opt => opt.MapFrom(src => DateTimeOffset.UtcNow))
            .ForMember(dest => dest.Success, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.Error, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.MessageId, opt => opt.Ignore()) // Set by service
            .ForMember(dest => dest.Document, opt => opt.Ignore());
    }
}
